"""baseline schema

Revision ID: 4058e1b3d445
Revises: 
Create Date: 2026-07-21 11:06:54.523709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4058e1b3d445'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(length=150), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('institution_name', sa.String(length=150), nullable=True),
    sa.Column('last4_masked', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('budget_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_group', sa.String(length=50), nullable=True),
    sa.Column('is_system_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('chat_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_offsets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('credit_transaction_id', sa.String(), nullable=False),
    sa.Column('matched_expense_id', sa.String(), nullable=True),
    sa.Column('matched_category', sa.String(length=100), nullable=True),
    sa.Column('credit_type', sa.String(length=50), nullable=True),
    sa.Column('eligible_for_matching', sa.Integer(), nullable=True),
    sa.Column('applied_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unapplied_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('match_confidence', sa.String(length=20), nullable=True),
    sa.Column('match_method', sa.String(length=50), nullable=True),
    sa.Column('statement_period', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('matched_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_fixed_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_keyword', sa.Text(), nullable=False),
    sa.Column('is_fixed', sa.Integer(), nullable=False),
    sa.Column('user_confirmed', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('match_field', sa.Text(), nullable=True),
    sa.Column('match_value', sa.Text(), nullable=True),
    sa.Column('match_type', sa.Text(), nullable=True),
    sa.Column('transaction_type', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence_override', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('filter_accounts', sa.Text(), nullable=True),
    sa.Column('filter_start_date', sa.Date(), nullable=True),
    sa.Column('filter_end_date', sa.Date(), nullable=True),
    sa.Column('filter_categories', sa.Text(), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_rules',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('match_field', sa.String(length=50), nullable=True),
    sa.Column('match_operator', sa.String(length=30), nullable=True),
    sa.Column('match_value', sa.String(length=255), nullable=False),
    sa.Column('output_transaction_type', sa.String(length=50), nullable=True),
    sa.Column('output_category', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('apply_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('uploaded_files',
    sa.Column('uploaded_file_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=30), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('upload_status', sa.String(length=30), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('transactions_extracted', sa.Integer(), nullable=True),
    sa.Column('duplicates_skipped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uploaded_file_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('income_amount', sa.Float(), nullable=True),
    sa.Column('income_frequency', sa.String(length=30), nullable=True),
    sa.Column('savings_goal_weekly', sa.Float(), nullable=True),
    sa.Column('savings_goal_monthly', sa.Float(), nullable=True),
    sa.Column('debt_payoff_goal', sa.Float(), nullable=True),
    sa.Column('financial_goal', sa.String(length=100), nullable=True),
    sa.Column('selected_goals', sa.Text(), nullable=True),
    sa.Column('other_goals', sa.Text(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('monthly_budget', sa.Float(), nullable=True),
    sa.Column('payday_day', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('uploaded_file_id', sa.String(), nullable=True),
    sa.Column('external_transaction_id', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('bank_source', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('exclusion_reason', sa.String(length=100), nullable=True),
    sa.Column('classification_confidence', sa.String(), nullable=True),
    sa.Column('import_source', sa.String(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('fixed_confidence', sa.Float(), nullable=True),
    sa.Column('fixed_source', sa.String(), nullable=True),
    sa.Column('fixed_suggestion_dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('fingerprint', 'user_id', name='uq_txn_fingerprint_user'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_fingerprint'), ['fingerprint'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_fingerprint'))

    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_table('uploaded_files')
    op.drop_table('transaction_rules')
    op.drop_table('projects')
    op.drop_table('merchant_rules')
    op.drop_table('manual_fixed_expenses')
    op.drop_table('credit_offsets')
    op.drop_table('chat_log')
    op.drop_table('categories')
    op.drop_table('budget_history')
    op.drop_table('accounts')
    # ### end Alembic commands ###
